# Grafana datasource provisioning configuration
# This file configures Prometheus as a data source for Grafana
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    httpMethod: GET
    basicAuth: false
    withCredentials: false
    jsonData:
      httpMethod: GET
      timeInterval: "30s"