package com.enterprise.java.streaming.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.LocalDateTime;

/**
 * Alert event model for security and system alerts generated by stream processing.
 */
public class AlertEvent {
    
    @JsonProperty("alertId")
    private String alertId;
    
    @JsonProperty("userId")
    private String userId;
    
    @JsonProperty("alertType")
    private String alertType;
    
    @JsonProperty("description")
    private String description;
    
    @JsonProperty("timestamp")
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    private LocalDateTime timestamp;
    
    @JsonProperty("severity")
    private String severity; // LOW, MEDIUM, HIGH, CRITICAL
    
    @JsonProperty("eventCount")
    private Integer eventCount;
    
    @JsonProperty("resolved")
    private boolean resolved = false;
    
    // Default constructor for Jackson
    public AlertEvent() {}
    
    // Constructor
    public AlertEvent(String alertId, String userId, String alertType, String description,
                     LocalDateTime timestamp, String severity, Integer eventCount) {
        this.alertId = alertId;
        this.userId = userId;
        this.alertType = alertType;
        this.description = description;
        this.timestamp = timestamp;
        this.severity = severity;
        this.eventCount = eventCount;
    }
    
    // Builder pattern
    public static Builder builder() {
        return new Builder();
    }
    
    public static class Builder {
        private String alertId;
        private String userId;
        private String alertType;
        private String description;
        private LocalDateTime timestamp;
        private String severity;
        private Integer eventCount;
        private boolean resolved = false;
        
        public Builder alertId(String alertId) {
            this.alertId = alertId;
            return this;
        }
        
        public Builder userId(String userId) {
            this.userId = userId;
            return this;
        }
        
        public Builder alertType(String alertType) {
            this.alertType = alertType;
            return this;
        }
        
        public Builder description(String description) {
            this.description = description;
            return this;
        }
        
        public Builder timestamp(LocalDateTime timestamp) {
            this.timestamp = timestamp;
            return this;
        }
        
        public Builder severity(String severity) {
            this.severity = severity;
            return this;
        }
        
        public Builder eventCount(Integer eventCount) {
            this.eventCount = eventCount;
            return this;
        }
        
        public Builder resolved(boolean resolved) {
            this.resolved = resolved;
            return this;
        }
        
        public AlertEvent build() {
            AlertEvent alert = new AlertEvent(alertId, userId, alertType, description, 
                                            timestamp, severity, eventCount);
            alert.setResolved(resolved);
            return alert;
        }
    }
    
    // Getters and setters
    public String getAlertId() {
        return alertId;
    }
    
    public void setAlertId(String alertId) {
        this.alertId = alertId;
    }
    
    public String getUserId() {
        return userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    
    public String getAlertType() {
        return alertType;
    }
    
    public void setAlertType(String alertType) {
        this.alertType = alertType;
    }
    
    public String getDescription() {
        return description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    public LocalDateTime getTimestamp() {
        return timestamp;
    }
    
    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }
    
    public String getSeverity() {
        return severity;
    }
    
    public void setSeverity(String severity) {
        this.severity = severity;
    }
    
    public Integer getEventCount() {
        return eventCount;
    }
    
    public void setEventCount(Integer eventCount) {
        this.eventCount = eventCount;
    }
    
    public boolean isResolved() {
        return resolved;
    }
    
    public void setResolved(boolean resolved) {
        this.resolved = resolved;
    }
    
    @Override
    public String toString() {
        return "AlertEvent{" +
                "alertId='" + alertId + '\'' +
                ", userId='" + userId + '\'' +
                ", alertType='" + alertType + '\'' +
                ", description='" + description + '\'' +
                ", timestamp=" + timestamp +
                ", severity='" + severity + '\'' +
                ", eventCount=" + eventCount +
                ", resolved=" + resolved +
                '}';
    }
}